name: Deploy Spring Boot App

on:
  push:
    paths:
      - 'aisearch/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot app
        working-directory: elastic-search
        run: |
          ./mvnw clean package -DskipTests

      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: "elastic-search/target/*.jar"
          target: "/var/www/springboot"
          overwrite: true

      - name: Restart App on Host
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            pkill -f 'java -jar' || true
            nohup java -Xmx1g -Xms512m -jar /var/www/springboot/*.jar > /var/www/springboot/log.txt 2>&1 &


