name: Deploy Spring Boot App

on:
  push:
    paths:
      - 'aisearch/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot app
        working-directory: aisearch
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: "aisearch/target/*.jar"
          target: "/var/www/springboot-uaisearch"
          overwrite: true
          strip_components: 2

      - name: Renomear arquivo e reiniciar serviço
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            sudo rm -f /var/www/springboot-uaisearch/backend.jar
            sudo mv /var/www/springboot-uaisearch/aisearch-0.0.1-SNAPSHOT.jar /var/www/springboot-uaisearch/backend.jar
            sudo systemctl restart uaisearch-backend.service
